version: '3'

services:
  telegram-bot:
    build: .
    container_name: telegram-bot
    #restart: unless-stopped
    environment:
      - CONFIG_PATH=/app/config/config.yaml
    volumes:
      - ./config/config.yaml:/app/config/config.yaml
      - /etc/ssl/certs/:/etc/ssl/certs/
